# Permalinks
permalink:        pretty

#For jekyll 2, becuse was commented
#relative_permalinks: true

# Setup
title:            Proshik`s blog
tagline:          Development & DevOps
url:              http://proshik.github.io
description:      Proshik`s blog
paginate:         5
baseurl:          /

markdown: redcarpet

author:
  name:           Prokhor Krylov

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/proshik/proshik.github.io

#Links
pages_list:
  Archive: '/archive'
  Feed: '/feed.xml'
  About blog: '/about'


markdown: kramdown

gems :
  - jekyll-paginate