# Site settings
title: Proshik Inc
description: Development & DevOps
url: http://proshik.ru
baseurl: /
google_analytics: UA-75725805-1
disqus_shortname: proshik

author:
  name: 'Prokhor Krylov'
  email: proxoraleksandrovich@gmail.com
  twitter_username: proshik
  facebook_username: proshik
  github_username: proshik
  linkedin_username: prokhor-krylov-a02757a4?trk=hp-identity-name

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
