# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Записки начинающего программиста
tagline:          О том, что все нормальные люди запоминают, а я почему-то не могу
url:              http://proshik.github.io
paginate:         2
baseurl:          /

markdown: redcarpet

author:
  name:           Proxor Krylov

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/proshik/proshik.github.io

#Links
pages_list:
  Архив: '/archive'
  О блоге: '/about'

markdown: redcarpet