# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            На потом о java, linux
tagline:          'А то детали всегда забываются'
url:              http://proshik.github.io
paginate:         10
baseurl:          /

author:
  name:           Proxor Krylov
  url:            https://twitter.com/proshik

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/proshik/proshik.github.io

#Links
pages_list:
  Архив записей: '/archive'
  О блоге: '/about'
